/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PrimeCheckbox: typeof import('primevue/checkbox')['default']
    PrimeCheckBox: typeof import('primevue/checkbox')['default']
    PrimeCheckBoxGroup: typeof import('primevue/checkboxgroup')['default']
    PrimeMenubar: typeof import('primevue/menubar')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
